spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Zak Islam - QA Lead"
    email: "Zak.islam@eazybank.com"
  onCallSupport:
    - 6016574682
    - 6045674655