build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Zak Islam - QA Lead"
    email: "Zak.islam@eazybank.com"
  onCallSupport:
    - 6016574682
    - 6045674655