build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Najrul Islam - Developer"
    email: "najrul.islam@eazybank.com"
  onCallSupport:
    - 2158829865
    - 2674564865