server:
  port: 8081
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  config:
    #optional helps with running even if the api is not accessible
    import: "optional:configserver:http://localhost:8071/"

  # This rabbit MQ helps with automatically invoking the refresh endpoint of the actuator of our microservices.
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# Enables all the endpoints of the actuator
management:
  endpoints:
    web:
      exposure:
        # If you want to specify what to expose (ex. refresh) example is below. * will include everything actuator has to offer.
        #include: "refresh"
        include: "*"