services:
# Configuration for accounts containers
  accounts:
    image: "najrulbiplob/accounts:s4"
    container_name: account-ms
    ports:
    - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

# Configuration for loans containers
  loans:
    image: "najrulbiplob/loans:s4"
    container_name: loans-ms
    ports:
    - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

# Configuration for cards containers
  cards:
    image: "najrulbiplob/cards:s4"
    container_name: cards-ms
    ports:
    - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

#
networks:
  eazybank:
    driver: "bridge"