services:

  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  # Configuration for configserver
  configserver:
    image: "najrulbiplob/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    # This healthcheck helps with testing if the configserver is ready with the configs or not.
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      # Execute the healthcheck {start_period} after the 10 seconds. If there is failure retires of 10 times, interval of 10 seconds and timeout in 5 seconds.
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


# Configuration for accounts containers
  accounts:
    image: "najrulbiplob/accounts:s7"
    container_name: account-ms
    ports:
    - "8080:8080"
    # {healthcheck of configserver} Below configs helps with checking service status of the configserver
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    depends_on:
      accountsdb:
        condition: service_healthy
    # This extends will help with reading repeating details from the common-config.yml file
    extends:
      file: common-config.yml
      service: microservice-configserver-config

# Configuration for loans containers
  loans:
    image: "najrulbiplob/loans:s7"
    container_name: loans-ms
    ports:
    - "8090:8090"
    # {healthcheck of configserver} Below configs helps with checking service status of the configserver
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    depends_on:
      loansdb:
        condition: service_healthy
    # This extends will help with reading repeating details from the common-config.yml file
    extends:
      file: common-config.yml
      service: microservice-configserver-config

# Configuration for cards containers
  cards:
    image: "najrulbiplob/cards:s7"
    container_name: cards-ms
    ports:
    - "9000:9000"
    # {healthcheck of configserver} Below configs helps with checking service status of the configserver
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    depends_on:
      cardsdb:
        condition: service_healthy
    # This extends will help with reading repeating details from the common-config.yml file
    extends:
      file: common-config.yml
      service: microservice-configserver-config


# This helps with having all the microservices in the same network.
networks:
  eazybank:
    driver: "bridge"