server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # This will import the other yml files that are in resources. Profile active will help with which profile details should be used (VM: -D Ex. -Dspring.profiles.active=prod -Dbuild.version=1.3) (Program Argument: -- Ex. --spring.profiles.active=qa --build.version=2.1)
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      #- "qa"
      #--spring.profiles.active=prod --build.version=3.333333
      #-Dspring.profiles.active=qa -Dbuild.version=2.222222

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Najrul Islam - Developer"
    email: "najrul.islam@eazybank.com"
  onCallSupport:
    - 2674684574
    - 2110546587