server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    # Mysql db related information
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  # H2 DB related information
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
    #username: sa
    #password:
  #h2:
    #console:
      #enabled: true
  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
      #ddl-auto: update
      #show-sql: true

  config:
    #optional helps with running even if the api is not accessible. after optional the configserver is a must regardless of what the name of the config server is.
    import: "optional:configserver:http://localhost:8071/"

# Enables all the endpoints of the actuator
management:
  endpoints:
    web:
      exposure:
        # If you want to specify what to expose (ex. refresh) example is below. * will include everything actuator has to offer.
        #include: "refresh"
        include: "*"




        #docker command for the rabbit MQ: docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.13-management