server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    # Mysql db related information
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    #optional helps with running even if the api is not accessible. after optional the configserver is a must regardless of what the name of the config server is.
    import: "optional:configserver:http://localhost:8071/"

# Enables all the endpoints of the actuator
management:
  endpoints:
    web:
      exposure:
        # If you want to specify what to expose (ex. refresh) example is below. * will include everything actuator has to offer.
        #include: "refresh"
        include: "*"